# Introduction

# Step 0

In [ ]:
import pandas as pd
import numpy as np

from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from numpy import linalg as LA
import matplotlib.pyplot as plt

from sklearn.decomposition import FactorAnalysis
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import f1_score

In [ ]:
# Step 0
# Load the data

In [ ]:
df = pd.read_csv('/content/sample_data/houses-prices.csv')

# Step 1

In [ ]:
# Step 1
# Start to understand them :
#    - In a business way (description, google, ...) 
#    - In a mathematical way (correlation between them, range, mean , type, ...)

In [ ]:
df.corr()['SalePrice']

Id              -0.021917
MSSubClass      -0.084284
LotFrontage      0.351799
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
MasVnrArea       0.477493
BsmtFinSF1       0.386420
BsmtFinSF2      -0.011378
BsmtUnfSF        0.214479
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
BsmtHalfBath    -0.016844
FullBath         0.560664
HalfBath         0.284108
BedroomAbvGr     0.168213
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageYrBlt      0.486362
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
OpenPorchSF      0.315856
EnclosedPorch   -0.128578
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [ ]:
columns_str=['MSZoning','Street','Alley',
            'LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood',
             'Condition1','Condition2','BldgType','HouseStyle',
            'RoofStyle','RoofMatl','Exterior1st',"Exterior2nd","MasVnrType","ExterQual",
            'ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure',
            'BsmtFinType1','BsmtFinType2','Heating','HeatingQC','Electrical',
            'KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish',
            'GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature',
            'SaleType','SaleCondition']

col_bin=["CentralAir"]

In [ ]:
str_keys=pd.DataFrame(columns=columns_str)
max_len=0
my_list=[]
for i in columns_str:
    unique_len=len(df[i].unique())
    if unique_len>max_len:
        max_len=unique_len
for i in columns_str:
    temp=[]
    for u in range(max_len):
        if u >= len(df[i].unique()):
            temp.append(np.nan)
        else:
            temp.append(df[i].unique()[u])
    my_list.append(temp)

In [ ]:
np.asarray(my_list)

array([['RL', 'RM', 'C (all)', ..., 'nan', 'nan', 'nan'],
       ['Pave', 'Grvl', 'nan', ..., 'nan', 'nan', 'nan'],
       ['nan', 'Grvl', 'Pave', ..., 'nan', 'nan', 'nan'],
       ...,
       ['nan', 'Shed', 'Gar2', ..., 'nan', 'nan', 'nan'],
       ['WD', 'New', 'COD', ..., 'nan', 'nan', 'nan'],
       ['Normal', 'Abnorml', 'Partial', ..., 'nan', 'nan', 'nan']],
      dtype='<U7')

In [ ]:
str_keys=pd.DataFrame(columns=columns_str)
for i,u in enumerate(columns_str):
    str_keys[u]=np.asarray(my_list[i])

In [ ]:
for ind,col in enumerate(df.columns):
    if col in columns_str:
        num=str_keys[col].dropna().index
        val=str_keys[col].dropna().values
        df.iloc[:,ind]=df[col].replace(val,num)

In [ ]:
str_keys

   MSZoning Street Alley LotShape  ...  Fence MiscFeature SaleType SaleCondition
0        RL   Pave   nan      Reg  ...    nan         nan       WD        Normal
1        RM   Grvl  Grvl      IR1  ...  MnPrv        Shed      New       Abnorml
2   C (all)    nan  Pave      IR2  ...   GdWo        Gar2      COD       Partial
3        FV    nan   nan      IR3  ...  GdPrv        Othr    ConLD       AdjLand
4        RH    nan   nan      nan  ...   MnWw        TenC    ConLI        Alloca
5       nan    nan   nan      nan  ...    nan         nan      CWD        Family
6       nan    nan   nan      nan  ...    nan         nan    ConLw           nan
7       nan    nan   nan      nan  ...    nan         nan      Con           nan
8       nan    nan   nan      nan  ...    nan         nan      Oth           nan
9       nan    nan   nan      nan  ...    nan         nan      nan           nan
10      nan    nan   nan      nan  ...    nan         nan      nan           nan
11      nan    nan   nan      nan  ...    nan         nan      nan           nan
12      nan    nan   nan      nan  ...    nan         nan      nan           nan
13      nan    nan   nan      nan  ...    nan         nan      nan           nan
14      nan    nan   nan      nan  ...    nan         nan      nan           nan
15      nan    nan   nan      nan  ...    nan         nan      nan           nan
16      nan    nan   nan      nan  ...    nan         nan      nan           nan
17      nan    nan   nan      nan  ...    nan         nan      nan           nan
18      nan    nan   nan      nan  ...    nan         nan      nan           nan
19      nan    nan   nan      nan  ...    nan         nan      nan           nan
20      nan    nan   nan      nan  ...    nan         nan      nan           nan
21      nan    nan   nan      nan  ...    nan         nan      nan           nan
22      nan    nan   nan      nan  ...    nan         nan      nan           nan
23      nan    nan   nan      nan  ...    nan         nan      nan           nan
24      nan    nan   nan      nan  ...    nan         nan      nan           nan

[25 rows x 42 columns]

In [ ]:
df

        Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
0        1          60         0  ...         0              0     208500
1        2          20         0  ...         0              0     181500
2        3          60         0  ...         0              0     223500
3        4          70         0  ...         0              1     140000
4        5          60         0  ...         0              0     250000
...    ...         ...       ...  ...       ...            ...        ...
1455  1456          60         0  ...         0              0     175000
1456  1457          20         0  ...         0              0     210000
1457  1458          70         0  ...         0              0     266500
1458  1459          20         0  ...         0              0     142125
1459  1460          20         0  ...         0              0     147500

[1460 rows x 81 columns]

In [ ]:
df.describe()

                Id   MSSubClass  ...  SaleCondition      SalePrice
count  1460.000000  1460.000000  ...     1460.00000    1460.000000
mean    730.500000    56.897260  ...        0.35000  180921.195890
std     421.610009    42.300571  ...        0.88787   79442.502883
min       1.000000    20.000000  ...        0.00000   34900.000000
25%     365.750000    20.000000  ...        0.00000  129975.000000
50%     730.500000    50.000000  ...        0.00000  163000.000000
75%    1095.250000    70.000000  ...        0.00000  214000.000000
max    1460.000000   190.000000  ...        5.00000  755000.000000

[8 rows x 80 columns]

# Step 2

In [ ]:
# Step 2
# Choose a problem :
# - Price prediction based on caracteristic (Regression problem)

Comments

# Step 3

In [ ]:
# Step 3
# Try a naive way to first get a firstscore (the least with no real improvement) :
#   Use the simplest algorithm
#   Use raw data (no improvement, don't use if it's not fitting)
#   train and score using train test spliting

# measure the performances :
# Score of prediction (choose depending on your probleme, precision or F1)
# time to train
# time to predict

# We will uses theses metrics to track our improvement :

## test on raw data

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
df=df.apply(pd.to_numeric, errors='coerce')
df=df.fillna(0)
df

        Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
0        1          60         0  ...         0              0     208500
1        2          20         0  ...         0              0     181500
2        3          60         0  ...         0              0     223500
3        4          70         0  ...         0              1     140000
4        5          60         0  ...         0              0     250000
...    ...         ...       ...  ...       ...            ...        ...
1455  1456          60         0  ...         0              0     175000
1456  1457          20         0  ...         0              0     210000
1457  1458          70         0  ...         0              0     266500
1458  1459          20         0  ...         0              0     142125
1459  1460          20         0  ...         0              0     147500

[1460 rows x 81 columns]

In [ ]:
df2 = df.copy()

In [ ]:
size=len(df)
X_train=np.asarray(df2.drop(columns='SalePrice').iloc[:int(0.7*size),:])
Y_train=np.asarray(df2['SalePrice'].iloc[:int(0.7*size)])

X_test=np.asarray(df2.drop(columns='SalePrice').iloc[int(0.7*size):,:])
Y_test=np.asarray(df2['SalePrice'].iloc[int(0.7*size):])

In [ ]:
reg = LinearRegression().fit(X_train, Y_train)
reg.score(X_test, Y_test)

0.585541768917838

# Step 4

In [ ]:
# Step 4
# Try to reduced the dataset using a naive way (techniques seen in courses 2 - features selections)
# measure the naive algorithm performances on this REDUCED dataset:
# Score of prediction (choose depending on your probleme, precision or F1)
# time to train
# size of reduced dataset

# We will uses theses metrics to track our improvement :

Feature selction using SelectFromModel

In order to keep fetures which really matters for our prediction, we will select only certain fetures thanks to a true or false list. This list would be a naive way of choosing the right to keep. 

We use the SelectFromModel but we could have chosen others. This one is more mathematics.

We drop first our target. And define it as the target.

In [ ]:
df3 = df.copy()

In [ ]:
df3_features = df3.drop(columns='SalePrice')
df3_target = df3['SalePrice']


df3_columns = list(df.columns)
df3_columns2 = df3_columns.remove('SalePrice')
print(df3_columns)

['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition']

We apply again the Linear Regression as an estimator.

In [ ]:
# Choose and load the estimator / model
linear_regression_estimator = LinearRegression()

# Load the selector
select_from_model_selector = SelectFromModel(linear_regression_estimator, max_features=5, threshold=-np.inf)

# Fit the selector on data
select_from_model_selector.fit(df3_features, df3_target)

Let's create a new dataframe with the columns corresponding to all the features, their coefficient associated and if they are selected or not (with True or False).

In [ ]:
# Gather the features selected
df3_features_selected = pd.DataFrame(df3_columns,columns=["features"])

# display the coeff, the features and the selected status
df3_features_selected['coeff'] = select_from_model_selector.estimator_.coef_
df3_features_selected['is_selected'] = select_from_model_selector.get_support()

Now, we can see which features would be relevant to select. We observe that these features are the most correlate to the sale price : 
- KitchenAbvGr : kitchens abode grade
- OverallQual : rates the orverall material and finish of the house
- Utilities 
- PoolQC : Pool quality
- Street

In [ ]:

df3_features_selected.sort_values('is_selected', ascending = False,inplace=True)
print(df3_features_selected)

         features          coeff  is_selected
52   KitchenAbvGr  -19167.092670         True
17    OverallQual   13776.473338         True
9       Utilities  -57393.123733         True
72         PoolQC -189346.928836         True
5          Street  -35547.452775         True
..            ...            ...          ...
76         MoSold     -25.640074        False
77         YrSold     -85.546849        False
78       SaleType    2500.578872        False
62     GarageArea       8.597381        False
79  SaleCondition     643.576122        False

[80 rows x 3 columns]

Let's try hte RFE on our dataset. The RFE is the recursive feature elimination. It removes each features based on their coef score provide by the estimator (ie LR or SVC) : the feature with the lowest coef is removed. Improvement is'nt based on the model score, but on the model coef calculation : The RFE choice the features depending on model, it's not always relevant.

In [ ]:
# Load the selector on a defined number of feature to select
rfe_selector = RFE(linear_regression_estimator, n_features_to_select=4)
# fit on train set
fited_rfe_selector = rfe_selector.fit(df3_features, df3_target)

In [ ]:

df3_features_selected['ranking'] = fited_rfe_selector.ranking_
df3_features_selected.sort_values('ranking', inplace=True)

print(df3_features_selected)

         features         coeff  is_selected  ranking
16     HouseStyle    314.098266        False        1
7        LotShape   1480.345616        False        1
63     GarageQual   6557.564331        False        1
10      LotConfig   1011.916290        False        1
47   BsmtFullBath   6563.000064        False        2
..            ...           ...          ...      ...
76         MoSold    -25.640074        False       73
5          Street -35547.452775         True       74
68  EnclosedPorch     -0.157509        False       75
52   KitchenAbvGr -19167.092670         True       76
12   Neighborhood   -276.720543        False       77

[80 rows x 4 columns]

# Step 5

In [ ]:
# Step 5
# based on you first discovery, clean and enhanced data :
#    - convert label into number
#    - add features (calculated from other, look on hide information )
#    -  ...

# Step 6

In [ ]:
# Step 6
# Try to improve your SCORE on ENHANCED dataset :
# using your first algorithm
# using other algorithm

# for each model/algorithm, measure the performances :
# Score of prediction (choose depending on your probleme, precision or F1)
# time to train
# size of used dataset

In [ ]:
df4 = df.copy()

# we check that there is no nan and inf
df4[~df4.isin([np.nan, np.inf, -np.inf]).any(1)]

# we put everything in float
df4= df4.astype(float)

print(df4)

          Id  MSSubClass  MSZoning  ...  SaleType  SaleCondition  SalePrice
0        1.0        60.0       0.0  ...       0.0            0.0   208500.0
1        2.0        20.0       0.0  ...       0.0            0.0   181500.0
2        3.0        60.0       0.0  ...       0.0            0.0   223500.0
3        4.0        70.0       0.0  ...       0.0            1.0   140000.0
4        5.0        60.0       0.0  ...       0.0            0.0   250000.0
...      ...         ...       ...  ...       ...            ...        ...
1455  1456.0        60.0       0.0  ...       0.0            0.0   175000.0
1456  1457.0        20.0       0.0  ...       0.0            0.0   210000.0
1457  1458.0        70.0       0.0  ...       0.0            0.0   266500.0
1458  1459.0        20.0       0.0  ...       0.0            0.0   142125.0
1459  1460.0        20.0       0.0  ...       0.0            0.0   147500.0

[1460 rows x 81 columns]

In [ ]:
df4_features = df4.drop('SalePrice', axis=1)
df4_target = df4['SalePrice']
print(df4_features)

          Id  MSSubClass  MSZoning  ...  YrSold  SaleType  SaleCondition
0        1.0        60.0       0.0  ...  2008.0       0.0            0.0
1        2.0        20.0       0.0  ...  2007.0       0.0            0.0
2        3.0        60.0       0.0  ...  2008.0       0.0            0.0
3        4.0        70.0       0.0  ...  2006.0       0.0            1.0
4        5.0        60.0       0.0  ...  2008.0       0.0            0.0
...      ...         ...       ...  ...     ...       ...            ...
1455  1456.0        60.0       0.0  ...  2007.0       0.0            0.0
1456  1457.0        20.0       0.0  ...  2010.0       0.0            0.0
1457  1458.0        70.0       0.0  ...  2010.0       0.0            0.0
1458  1459.0        20.0       0.0  ...  2010.0       0.0            0.0
1459  1460.0        20.0       0.0  ...  2008.0       0.0            0.0

[1460 rows x 80 columns]

We drop the columns if the present the same values

In [ ]:
#df4_features = df4.drop('MSZoning')
#, 'SaleType', 'Street', 'Alley', 'LandContour', 'Utilities','LandSlope'

KeyError: ignored

In [ ]:
#using linalg from numpy, extract the eigen values from the avocado dataset

values = LA.eigvals(df4_features.corr())

LinAlgError: ignored

In [ ]:
# using Matplotlib or Seaborn, draw a scree plot of the previous calculated eigen values

plt.scatter(range(1,values.size+1),values)
plt.plot(range(1,values.size+1),values)
plt.hlines(1, 0, values.size, colors='r')
plt.title('Scree Plot')
plt.xlabel('Factors')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

How many to keep if we want to reduce the dataset?

In [ ]:
df4_features_columns = list(df4_features.columns)

# use the train_test_split function to create 4 dataset :
# avocado_features_train, avocado_features_test, avocado_target_train, avocado_target_test
df4_features_train, df4_features_test, df4_target_train, df4_target_test = train_test_split(df4_features, df4_target, test_size=0.20, random_state=42)

# initiate the LinearSVC model
linear_svc_model = LinearSVC()
# fit the data on the train data and target
linear_svc_model.fit(df4_features_train,df4_target_train)
#Score the prediction score on the test data and target
print(linear_svc_model.score(df4_features_test,df4_target_test))

df4_target_predicted = linear_svc_model.predict(df4_features_test)

print(f1_score(df4_target_test, df4_target_predicted, average='weighted'))

0.0
0.0

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

 In this contexte, the algorithm doesn't perform well
The linear SVC use distance calculation to perform its prediction.
we are going to normalize or data in order to reduce the value of the distance

In [ ]:

# use the StandardScaler to remove the mean and scaling data to unit variance
scaler = StandardScaler()
#calculating the mean and variance
scaler.fit(df4_features)
#removing the mean and scaling to unit variance
scaled_df4_features = scaler.transform(df4_features)

# Do the procedure to create the 4 datasets, train the model and score its prediction

scaled_df4_features_train, scaled_df4_features_test, df4_target_train, df4_target_test = train_test_split(scaled_df4_features, df4_target, test_size=0.20, random_state=42)

linear_svc_model = LinearSVC()
linear_svc_model.fit(scaled_df4_features_train,df4_target_train)


print(linear_svc_model.score(scaled_df4_features_test,df4_target_test))


print(f1_score(df4_target_test,linear_svc_model.predict(scaled_df4_features_test),average='weighted'))

0.0
0.0

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [ ]:
# Now that we have a score for comparaison, we are going to reduced the dataset using the factor
# and we are going to score the prediction using the reduced data set

# use the StandardScaler to remove the mean and scaling data to unit variance
scaler = StandardScaler()
#calculating the mean and variance
scaler.fit(df4_features)
#removing the mean and scaling to unit variance
scaled_df4_features = scaler.transform(df4_features)

# create the FactorAnalysis and fit it on the dataset in order to have a new dataset with only 6 columns
factor_analysis_df4 = FactorAnalysis(n_components = 6).fit(scaled_df4_features)
# create a transformed_scaled_avocado_features dataset using the FactorAnalysis previously created
transformed_scaled_df4_features = factor_analysis_df4.transform(scaled_df4_features)

# Do the procedure to create the 4 datasets, train the model and score its prediction
transformed_scaled_df4_features_train, transformed_scaled_df4_features_test, df4_target_train, df4_target_test = train_test_split(transformed_scaled_df4_features, df4_target, test_size=0.20, random_state=42)

linear_svc_model = LinearSVC()
linear_svc_model.fit(transformed_scaled_df4_features_train,df4_target_train)

#print(linear_svc_model.score(transformed_scaled_avocado_features_test,avocado_target_test))

print(f1_score(df4_target_test, linear_svc_model.predict(transformed_scaled_df4_features_test), average='weighted'))


# what do you think about this score compare to the 'optimal' one ?

0.0018873668188736682

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

# Step 7

In [ ]:
# Step 7
# Try to reduced the dataset using a smarter technique (SVD, FA, PCA)
# Try to improve your SCORE, TIME TRAINED on ENHANCED dataset :
# using your first algorithm
# using other algorithm

# for each model/algorithm, measure the performances with your REDUCED dataset:
# Score of prediction (choose depending on your probleme, precision or F1)
# time to train
# size of reduced dataset

In [ ]:
df=df.fillna(0)
#df=df.apply(float)
df['CentralAir']=df['CentralAir'].apply(clean)

In [ ]:
def clean(x):
    if x == 'N':
        return 0
    else :
        return 1

In [ ]:
from sklearn.decomposition import PCA
from numpy.linalg import svd
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt

In [ ]:
for i in df.columns:
    df[i]=df[i]-df[i].mean()
    df[i]=df[i]/df[i].var()

In [ ]:
X=df.drop(columns='SalePrice')

In [ ]:
#
# Scale the dataset; This is very important before you apply PCA
#
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)

pca = PCA()
#
# Determine transformed features
#
X_train_pca = pca.fit_transform(X)
#
# Determine explained variance using explained_variance_ration_ attribute
#
exp_var_pca = pca.explained_variance_ratio_
#
# Cumulative sum of eigenvalues; This will be used to create step plot
# for visualizing the variance explained by each principal component.
#
cum_sum_eigenvalues = np.cumsum(exp_var_pca)
#
# Create the visualization plot
#
plt.bar(range(0,len(exp_var_pca)), exp_var_pca, alpha=0.5, align='center', label='Individual explained variance')
plt.step(range(0,len(cum_sum_eigenvalues)), cum_sum_eigenvalues, where='mid',label='Cumulative explained variance')
plt.ylabel('Explained variance ratio')
plt.xlabel('Principal component index')
plt.legend(loc='best')
plt.tight_layout()
plt.show()

In [ ]:
pca = PCA(n_components=3)
pca.fit(X)
X_transformed = pca.transform(X)

In [ ]:
X_transformed

# Step 8

In [ ]:
# Step 8 
# Choose the best reduced algorithm based on metrics (score, time computing, size)
# Explain the business signification for any feature/Factor/Component of this reduced data set

# Step 9

In [ ]:
# Step 9
# Go back to step 5 and improve yout metrics !

# Step 10

In [ ]:
# Step 10

# find a way to present the work you did (video, notebook, powerpoint presentation, app, ...)